### ISSUE TITLE
Event second parameter can be typed?

### ISSUE THREAD

**Issue by b0c1** [yanchenko/droidparts#29]
Hi!

Can I use typed parameter instead of Object? example:
```java
@ReceiveEvents
private void onAnyEvent(String eventName, ConreteType eventData) {
   // TODO process any event with optional data
}
```

**Comment by yanchenko** [comment]
Hello, yes, it can.
Here's an example: https://github.com/yanchenko/droidparts/blob/master/droidparts-samples/DroidPartsGram/src/org/droidparts/gram/activity/MainActivity.java#L33
