### ISSUE TITLE
postEventSticky bug

### ISSUE THREAD

**Issue by Dmitry1155** [yanchenko/droidparts#30]
public static void postEventSticky(String name) {
		postEventSticky(name, null);
	}

but

@throws NullPointerException if the specified key or value is null

for ConcurrentHashMap 

in

public static void postEventSticky(String name, Object data) {
		stickyEvents.put(name, data);
		postEvent(name, data);
	}
----------------------
possible solution: 
public static void postEventSticky(String name) {
		postEventSticky(name, "");
	}

**Comment by yanchenko** [comment]
Thanks.
