### ISSUE TITLE
How to use the clear button for a multiline edit text?(Clearable edittext)

### ISSUE THREAD

**Issue by gvsharma** [yanchenko/droidparts#32]
Hi..
First of all thanks for this(Clearable Edittext). I have used this in my app and i want to use this for a multiline editext , and in that i want to place the drawable at the end? For a single line Edittext it works fine.

**Comment by yanchenko** [comment]
You can specify the number of lines like for a usual TextView. Please use http://stackoverflow.com/questions/tagged/droidparts for questions.
