### ISSUE TITLE
2.7.0 was built with 1.8 JDK - thus causing errors.

### ISSUE THREAD

**Issue by Atrinax** [yanchenko/droidparts#34]
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet
System.err﹕ at org.droidparts.bus.EventBus.unregisterAnnotatedReceiver(EventBus.java:121)
![image](https://cloud.githubusercontent.com/assets/7588223/6775248/4a906e38-d158-11e4-9172-477c7abd5e6c.png)

**Comment by yanchenko** [comment]
Thanks, build 2.7.1.
