### ISSUE TITLE
MultiSelectListPreference missing @Override setEntryValues 

### ISSUE THREAD

**Issue by fxhartmann** [yanchenko/droidparts#35]
Hi Alex,

I added to your Source MultiSelectListPreference.java the method:

	@Override
	public void setEntryValues(CharSequence[] entryValues) {
		super.setEntryValues(entryValues);
		updateCheckedEntryIndexes();
	}

Otherwise there is a problem in case sombody tries to reload the underlying List dynamically with more entryValues/entries.

If I load the new (bigger) list in the order 

        	mlp.setEntries(entries);
        	mlp.setEntryValues(entryValues);

it works fine.

But if I load the list by calling 

        	mlp.setEntryValues(entryValues);
        	mlp.setEntries(entries);

I run in an OutOfBoundException in the method 'getCheckedEntries()' because
the the variable this.checkedEntryIndexes is not consistent set to the new size.

With the correction mentioned above the classs variables are consisten.

Thanks for sharing your code.

Greetings Franz

**Comment by yanchenko** [comment]
Thanks!
Fixed in [35337b11f2296c776ad0120baa4bd862719fd0be].
