### ISSUE TITLE
[RFC] How to replace currently open SQLite database with backup?

### ISSUE THREAD

**Issue by vovan888** [yanchenko/droidparts#36]
Now I am trying to do it like so:
```Java
    Context context = Injector.getApplicationContext();
    Injector.tearDown();    // close all (and db too)
    replace_database_file();
    Injector.setUp(context);
```
But the program after this crashes on the first attempt to access database with exception:
java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase:

**Comment by yanchenko** [comment]
Привет.
Из какого места бросается Exception? Из какого-то EntityManager? Если да, то после замены базы его нужно пересоздать, т.к. существующий ссылается на старую (закрытую) базу.
Если нет, то что если в наследнике AbstractDependencyProvider вызвать close() и заменить базу? Injector не трогать.

**Comment by vovan888** [comment]
Exception возникает в EntityManager.
Я пока сделал доп метод:  DependencyProvider.updateDBOpenHelper(Context ctx) в котором пересоздаю DBOpenHelper и во всех наследниках EntityManager заменяю текущую базу доп методом EntityManager.setDB(SQLiteDatabase db). Вызываю это все через доп метод DependencyReader.updateDB(context)
Но как-то это громоздко получается...

**Comment by yanchenko** [comment]
В общем, да, как-то так. Суть в том, что нужно заменять базу до создания EntityManagers или же пересоздавать их, т.к. внутри ссылка на старую базу.

**Comment by vovan888** [comment]
Есть смысл делать пул-реквест с остальными моими изменениями для замены БД на лету ?

**Comment by yanchenko** [comment]
Привет, я думаю, что это очень частный случай, чтобы добавлять в основной проект.
Но буду очень благодарен, если добавишь описание процесса, возможно, с примером кода в https://github.com/yanchenko/droidparts.org/blob/master/orm.rst
Спасибо за фикс.

**Comment by vovan888** [comment]
Ок, это тебе спасибо за супер фреймворк!
