### ISSUE TITLE
Unable to use empty string as default value

### ISSUE THREAD

**Issue by Atrinax** [yanchenko/droidparts#38]
I've ran into that issue while trying to use addMissingColumns method:
```
android.database.sqlite.SQLiteException: near ";": syntax error (code 1): , 
while compiling: ALTER TABLE Table ADD COLUMN Column TEXT NOT NULL DEFAULT ;
```
It is definitely possible:
http://stackoverflow.com/questions/16606905/default-value-string-empty-in-sqlite-table
Column definition:
```Java
@Column
private String column = "";
```

**Comment by Atrinax** [comment]
Oh, and by the way, does your ORM set default values on database initial creation?
After the db dump I haven't found the use of default values, while I was actually trying to set them, for example:
@Column
@JSON
private String originCountry = "USA";

**Comment by yanchenko** [comment]
Thanks for the report.
The default value is only used when altering columns.
I've added a fix & published a snapshot. Should fix the issue. If not, please reopen.
