### ISSUE TITLE
App crash in IntentService

### ISSUE THREAD

**Issue by plzen** [yanchenko/droidparts#42]
Hello.

Found crash if IntentService gets intent=null.

https://github.com/yanchenko/droidparts/blob/master/droidparts/src/org/droidparts/concurrent/service/IntentService.java#L67
`String action = intent.getAction();`

Official docs http://developer.android.com/reference/android/app/IntentService.html#onStartCommand%28android.content.Intent,%20int,%20int%29

**Comment by yanchenko** [comment]
Thanks, fixed.
