### ISSUE TITLE
Clearable EditText as a separate library

### ISSUE THREAD

**Issue by evolutionise** [yanchenko/droidparts#44]
Hi,

The clearable edit text is a great piece of functionality - would you be interested in splitting it out as a separate library? I'd be happy to contribute/do it if you like.  I'm currently using a version in Kotlin based on what you've written and thought it might be useful to provide it for others as well.

**Comment by yanchenko** [comment]
Hello,
It's just one class (+ one class it relies on) which is unlikely to ever be modified. So I'd prefer to keep it where it is now. Feel free to create your own library based on my code.
