### ISSUE TITLE
Custom Primary Key

### ISSUE THREAD

**Issue by waqasahmadspace** [yanchenko/droidparts#45]
I am stuck with a scenario where I am bound to use a pre-defined database which has its primary keys already set. I have to manually insert column id in all the tables. Can you guys please get onto this problem. I mean either add an annotation of primary key so that people can override the default "id". Also its difficult to set a composite key. So, I have to manually handle this issue.

**Comment by AreebNetSol** [comment]
Any update on this?

**Comment by yanchenko** [comment]
Hello, having an _id column is required by other parts and it works in most of the cases so I'm not planning to change it.

What I can recommend is forking and changing the `Entity` class to make `public long id` optional.
Or, upon opening the database on a device for the first time, adding that column with unique ids (just a SQL statement in `DBOpenHelper`).
If you need a compound key, I recommend to use a unique index (e.g. [like here](https://github.com/yanchenko/droidparts/blob/master/droidparts-test/src/org/droidparts/test/persist/DBOpenHelper.java#L38)).
